name: "Check devDependencies"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Check devDependencies
      run: "node ./tools/check-dev-dependencies.js"
